/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as LoadoutsIndexRouteImport } from './pages/loadouts/index'
import { Route as LoadoutsLoadoutIdRouteImport } from './pages/loadouts/$loadoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsIndexRoute = LoadoutsIndexRouteImport.update({
  id: '/loadouts/',
  path: '/loadouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadoutsLoadoutIdRoute = LoadoutsLoadoutIdRouteImport.update({
  id: '/loadouts/$loadoutId',
  path: '/loadouts/$loadoutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loadouts/$loadoutId': typeof LoadoutsLoadoutIdRoute
  '/loadouts': typeof LoadoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loadouts/$loadoutId': typeof LoadoutsLoadoutIdRoute
  '/loadouts': typeof LoadoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loadouts/$loadoutId': typeof LoadoutsLoadoutIdRoute
  '/loadouts/': typeof LoadoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loadouts/$loadoutId' | '/loadouts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loadouts/$loadoutId' | '/loadouts'
  id: '__root__' | '/' | '/loadouts/$loadoutId' | '/loadouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadoutsLoadoutIdRoute: typeof LoadoutsLoadoutIdRoute
  LoadoutsIndexRoute: typeof LoadoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts/': {
      id: '/loadouts/'
      path: '/loadouts'
      fullPath: '/loadouts'
      preLoaderRoute: typeof LoadoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loadouts/$loadoutId': {
      id: '/loadouts/$loadoutId'
      path: '/loadouts/$loadoutId'
      fullPath: '/loadouts/$loadoutId'
      preLoaderRoute: typeof LoadoutsLoadoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadoutsLoadoutIdRoute: LoadoutsLoadoutIdRoute,
  LoadoutsIndexRoute: LoadoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
